version: '3'
services:
  my-angular11-experiment:
    container_name: my-angular11-experiment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
       - .:/app
