version: '3'
services:
  my-angular11-experiment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: my-angular11-experiment
    volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
